#!/bin/sh -e
#
# Copyright (C) 2017 Yousong Zhou <yszhou4tech@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
# Script for diverting selected traffics through vpn interface
#
#  - create and initialize ipset
#  - install netfilter/iptables rules to mark packets
#  - install ip rule and routes
#
# NOTE: it is not expected to work out of box
#

o_ifname="${o_ifname}"
o_gateway="${o_gateway}"
o_rttable="${o_rttable:-200}"
o_fwmark="${o_fwmark:-200}"
if [ -z "$o_ifname" ]; then
	exit 1
fi
o_without_recentrst="${o_without_recentrst}"
o_recentrst_filter=cat
if [ -n "$o_without_recentrst" ]; then
	o_recentrst_filter="grep -v recentrst"
fi
o_remote_servers="${o_remote_servers}"
o_dst_forward="${o_dst_forward-
	8.8.8.8
	1.1.1.1
}"
o_dst_bypass="
	${o_dst_bypass}
	0.0.0.0/8
	10.0.0.0/8
	100.64.0.0/10
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.0.0.0/24
	192.0.2.0/24
	192.31.196.0/24
	192.52.193.0/24
	192.88.99.0/24
	192.168.0.0/16
	192.175.48.0/24
	198.18.0.0/15
	198.51.100.0/24
	203.0.113.0/24
	224.0.0.0/4
	240.0.0.0/4
	255.255.255.255
"

__errmsg() {
	echo "vpnguru: $*" >&2
}

vpnguru_flush() {
	local setname

	iptables-save --counters | grep -v vpnguru_ | iptables-restore --counters
	while ip rule del fwmark "$o_fwmark" lookup "$o_rttable" 2>/dev/null; do true; done
	ip route flush table "$o_rttable"
	for setname in $(ipset -n list | grep "vpnguru_"); do
		ipset destroy "$setname" 2>/dev/null || true
	done
}

vpnguru_ipset_init() {
	$o_recentrst_filter <<-EOF | ipset --exist restore
		create vpnguru_dst_bypass hash:net hashsize 64
		create vpnguru_dst_forward hash:net hashsize 64
		create vpnguru_dst_forward_recentrst_ hash:ip hashsize 64 timeout 3600
		$(vpnguru_ipset_mkadd vpnguru_dst_bypass "$o_dst_bypass $o_remote_servers")
		$(vpnguru_ipset_mkadd vpnguru_dst_forward "$o_dst_forward")
	EOF
}

vpnguru_ipset_mkadd() {
	local setname="$1"; shift
	local i

	for i in $*; do
		echo "add $setname $i"
	done
}

vpnguru_iptchains_init() {
	$o_recentrst_filter <<-EOF | iptables-restore --noflush
		*mangle
		:vpnguru_mark -
		:vpnguru_mark_ -
		-I OUTPUT 1 -j vpnguru_mark_
		-I PREROUTING 1 -j vpnguru_mark
		-I FORWARD 1 -o $o_ifname -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "vpnguru_tcpmss" -j TCPMSS --clamp-mss-to-pmtu
		-A vpnguru_mark -j vpnguru_mark_
		-A vpnguru_mark -p tcp -m tcp --tcp-flags RST RST -m recent --name vpnguru_recentrst --set --rsource
		-A vpnguru_mark_ -m set --match-set vpnguru_dst_bypass dst -j RETURN
		-A vpnguru_mark_ -m set --match-set vpnguru_dst_forward dst -j MARK --set-mark $o_fwmark
		-A vpnguru_mark_ -m set --match-set vpnguru_dst_forward_recentrst_ dst -j MARK --set-mark $o_fwmark
		COMMIT
		*nat
		-I PREROUTING 1 -m recent --name vpnguru_recentrst --rcheck --rdest --seconds 3 --hitcount 3 -j SET --add-set vpnguru_dst_forward_recentrst_ dst --exist
		COMMIT
	EOF
}

vpnguru_route_init() {
	ip rule add fwmark "$o_fwmark" lookup "$o_rttable"
	ip route add default dev "$o_ifname" ${o_gateway:+via "$o_gateway"} table "$o_rttable"
	ip route flush cache
}

vpnguru_flush
vpnguru_ipset_init
vpnguru_iptchains_init
vpnguru_route_init
