#!/bin/bash

get() {
	# archlinuxarm has user accounts
	#
	#	alarm:alarm
	#	root:root
	#
	wget -c http://os.archlinuxarm.org/os/ArchLinuxARM-armv7-latest.tar.gz
}

prep() {
	sudo true

	bsdtar -xf ArchLinuxARM-armv7-latest.tar.gz \
		boot/initramfs-linux.img \
		boot/zImage \
		boot/dtbs/sun4i-a10-cubieboard.dtb \

	dd if=/dev/zero of=disk.img bs=4M count=512 conv=sync
	mkfs.ext4 disk.img
	mkdir -p disk
	sudo mount -o loop disk.img disk
	sudo bsdtar -xpf ArchLinuxARM-armv7-latest.tar.gz -C disk
	sudo umount disk/
}

r() {
	# To quash thermal_zone0 warning
	#
	#	echo disabled >/sys/class/thermal/thermal_zone0/mode
	#
	# Known issues
	#
	# - allwinner-emac driver cannot initialize mac address correctly
	# - varius kernel warning for missing devices
	# - no display support
	#
	qemu-system-arm \
		-M cubieboard \
		-m 1024M \
		-nographic \
		-initrd boot/initramfs-linux.img \
		-kernel boot/zImage \
		-dtb boot/dtbs/sun4i-a10-cubieboard.dtb \
		-append 'root=/dev/sda rootwait rw modprobe.blacklist=sun4i_ss,sunxi_cir,sun4i_gpadc,sun4i_codec' \
		-device ide-drive,drive=drv0 \
		-drive "file=disk.img,format=raw,id=drv0,if=none" \
		-net nic,macaddr=00:11:22:33:44:55,model=allwinner-emac,netdev=wan \
		-netdev bridge,id=wan,br=br-wan,helper=/home/yousong/.usr/libexec/qemu-bridge-helper \

}

"$@"
