name: Build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - testing
    paths:
      - docker/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: ./.github/workflows/docker-build-and-push.sh
