name: Build and push docker image

on:
  workflow_dispatch:
    inputs:
      dirs:
        description: 'Directories (separated by whitespace) containing Dockerfile'
        type: string
        default: ALL
        required: true
      is_testing:
        description: 'Build testing images'
        type: boolean
        default: false
        required: false
  push:
    branches:
      - testing
    paths:
      - docker/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        run: ./.github/workflows/docker-build-and-push.sh
        env:
          DOCKER_BUILD_AND_PUSH_DIRS: ${{ inputs.dirs }}
          DOCKER_BUILD_AND_PUSH_IS_TESTING: ${{ inputs.is_testing }}
